name: CoderCo Secret CI

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use secret 
        run: echo "The secret is ${{secrets.MY_SECRET}}"

      - name: use secrets as env var
        run: echo "The secret is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}